services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: washworld_flask
    depends_on:
      - mariadb
    ports:
      - "80:8080"
    env_file:
      - ./.env
    networks:
      - washworld-network
    cpus: "0.5"
    mem_limit: "512m"

  mariadb:
    image: mariadb:latest
    platform: ${DOCKER_PLATFORM}
    container_name: washworld_mariadb
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3308:3306"
    networks:
      - washworld-network
    cpus: "0.5"
    mem_limit: "512m"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: washworld_phpmyadmin
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8080:80"
    networks:
      - washworld-network
    cpus: "0.25"
    mem_limit: "256m"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
        NEXT_PUBLIC_MAPBOX_TOKEN: ${NEXT_PUBLIC_MAPBOX_TOKEN}
    container_name: washworld_frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - washworld-network
    cpus: "0.5"
    mem_limit: "512m"

networks:
  washworld-network:
    name: washworld-network

volumes:
  mariadb_data:
